### ISSUE TITLE
IAR:Select Configuration does not autopopulate with options

### ISSUE THREAD

**Issue by jbuckAI** [pluyckx/iar-vsc#38]
Great project, thanks!

IAR:Select Configuration would, assumedly, acts like other commands and auto populate options. This does not appear to happen. Any debug steps to help debug this issue?

**Comment by ben-edna** [comment]
Hi @jbuckAI, 

Some information that might help to investigate the issue:
- Did you do the `IAR: Select Project` before, so the plugin knows which `ewp` to parse the Configurations from?
- What version of IAR do you use?
- Do you have a (stripped) `ewp` file that can reproduce the issue?

**Comment by jbuckAI** [comment]
- I did select the project before
- I am using 8.32.2 (shows as Embedded Workbench 8.2_2)
- A simple project appears to mostly work (I can see the Release configure, not the Debug though). 
- The more complicated project does not show anything for configurations. The project file is generated by the [mbed CLI export](https://os.mbed.com/docs/mbed-os/v5.11/tools/exporting.html) functionality. mbedOS is huge and so it adds alot to the .ewp file. I am unsure how to strip to the bare essentials, I uploaded the whole thing though....
[mbed.zip](https://github.com/pluyckx/iar-vsc/files/2813566/mbed.zip)

Does this extension have any debug writes to the terminal that can help? I haven't had a chance to dive into the posted code...

**Comment by pluyckx** [comment]
Thank you for the ewp file. I can reproduce the issue and I also found what is wrong.
It seems there are no defines in the configuration and this triggers an exception in the extension. Because of this, configurations without at least one define are not loaded.

So a quick workaround is to just add at least one define in the preprocessor define list.

I will fix this issue on the master branch and create a new release on github in a couple of hours.
